# 빌드 스테이지
FROM maven:3.6 AS build
WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn clean package

# 실행 스테이지
FROM openjdk:11-jre-slim
WORKDIR /app

COPY --from=build /app/target/demo-0.0.1-SNAPSHOT.jar ./app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]