FROM maven:3.6-jdk-11
WORKDIR /app

COPY pom.xml .
COPY src ./src

# 의존성 + 빌드
RUN mvn clean package

# 파일 복사(빌드 컨텍스트 아니라, 내부적으ㅡ로 생성된 애플리케이션 파일 복사)
RUN cp /app/target/demo-0.0.1-SNAPSHOT.jar ./app.jar
EXPOSE 8000
CMD ["java", "-jar", "app.jar"]